[package]
name = "flash_extract"
version = "0.1.0"
authors = ["Ben-Lichtman <Ben_Lichtman@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
